language: emacs-lisp
notifications: { email: false }
branches: { only: travis }
before_install:
  - sudo apt-get build-dep -qq -y emacs
  - ./autogen.sh
script: ./configure --quiet && make --quiet && make check
